name: ci
on:
  push:
  pull_request:

jobs:
  backend:
    name: Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: pip
          cache-dependency-path: backend/requirements.txt
      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install pytest pytest-cov cyclonedx-bom bandit
      - name: Run tests
        run: |
          source .venv/bin/activate
          PYTHONPATH=$PWD pytest -q --maxfail=1 --disable-warnings --cov=app
#      - name: Generate SBOM
#        run: |
#          source .venv/bin/activate
#          python -m pip install --upgrade cyclonedx-bom
#          python -m cyclonedx_py --format json --output ../sbom.json
      - name: Bandit (security)
        run: |
          source .venv/bin/activate
          bandit -q -r app
