name: ci
on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install backend deps
        run: |
          cd backend
          python -m venv .venv
          . .venv/bin/activate
          pip install -r requirements.txt
          pip install pytest pytest-cov cyclonedx-bom bandit
      - name: Tests
        run: |
          cd backend
          . .venv/bin/activate
          PYTHONPATH=$PWD pytest -q --maxfail=1 --disable-warnings --cov=app
      - name: SBOM
        run: |
          cd backend
          . .venv/bin/activate
          python -m pip install --upgrade cyclonedx-bom
          python -m cyclonedx_py environment --format json --schema-version 1.4 --output ../sbom.json
      - name: Bandit (security)
        run: |
          cd backend
          . .venv/bin/activate
          bandit -q -r app || true
